### ISSUE TITLE
issues with firefox instances

### ISSUE THREAD

**Issue by yujulee** [LluisRamon/relenium#16]
I tried to use the package.  I got the following problem.  Can anyone else me?  Thanks in advance!

require(relenium)

firefox <- firefoxClass$new()

org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
lla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net
1412985692314   addons.xpi  WARN    Add-on webapps-team@lists.launchpad.net is missing bootstrap method install
1412985692314   addons.xpi  DEBUG   New add-on online-accounts@lists.launchpad.net installed in app-system-local
1412985692315   addons.xpi-utils    DEBUG   Make addon app-system-local:online-accounts@lists.launchpad.net visible
1412985692315   DeferredSave.extensions.json    DEBUG   Save changes
1412985692315   DeferredSave.extensions.json    DEBUG   Save changes
1412985692320   addons.xpi  DEBUG   Updating database with changes to installed add-ons
1412985692321   addons.xpi-utils    DEBUG   Updating add-on states
1412985692321   addons.xpi-utils    DEBUG   Writing add-ons list
1412985692321   addons.xpi  DEBUG   Registering manifest for /usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi
1412985692322   addons.xpi  DEBUG   Registering manifest for /usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi
1412985692524   DeferredSave.extensions.json    DEBUG   Starting timer
1412985692554   addons.manager  DEBUG   shutdown
1412985692555   DeferredSave.extensions.json    DEBUG   Starting write
1412985692555   addons.xpi  DEBUG   shutdown
1412985692555   addons.xpi-utils    DEBUG   shutdown
1412985692584   DeferredSave.extensions.json    DEBUG   Write succeeded
1412985692584   addons.xpi-utils    DEBUG   XPI Database saved, setting schema version preference to 16
1412985692585   addons.xpi  DEBUG   Notifying XPI shutdown observers
1412985692587   addons.manager  DEBUG   Async provider shutdown done

(process:4842): GLib-CRITICAL *_: g_slice_set_config: assertion 'sys_page_size == 0' failed
1412985692749   addons.manager  DEBUG   Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
1412985692750   addons.manager  DEBUG   Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1412985692751   addons.xpi  DEBUG   startup
1412985692751   addons.xpi  INFO    Mapping online-accounts@lists.launchpad.net to /usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/online-accounts@lists.launchpad.net
1412985692752   addons.xpi  INFO    Mapping {2e1445b0-2682-11e1-bfc2-0800200c9a66} to /usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{2e1445b0-2682-11e1-bfc2-0800200c9a66}
1412985692752   addons.xpi  INFO    Mapping ubufox@ubuntu.com to /usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com
1412985692752   addons.xpi  INFO    Mapping webapps-team@lists.launchpad.net to /usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net
1412985692753   addons.xpi  INFO    Mapping langpack-en-GB@firefox.mozilla.org to /usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi
1412985692754   addons.xpi  INFO    Mapping langpack-en-ZA@firefox.mozilla.org to /usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi
1412985692754   addons.xpi  INFO    Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to /usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}
1412985692755   addons.xpi  INFO    Mapping fxdriver@googlecode.com to /tmp/anonymous631912313451846625webdriver-profile/extensions/fxdriver@googlecode.com
1412985692756   addons.xpi  DEBUG   Ignoring file entry whose name is not a valid add-on ID: /tmp/anonymous631912313451846625webdriver-profile/extensions/webdriver-staging
1412985692756   addons.xpi  DEBUG   checkForChanges
1412985692762   addons.xpi  DEBUG   No changes found
1412985692764   addons.xpi  DEBUG   Registering manifest for /usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi
1412985692765   addons.xpi  DEBUG   Registering manifest for /usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi
*_\* Blocklist::_preloadBlocklistFile: blocklist is disabled
JavaScript error: chrome://browser/content/urlbarBindings.xml, line 677: aUrl is undefined
JavaScript error: chrome://browser/content/urlbarBindings.xml, line 677: aUrl is undefined
JavaScript error: chrome://browser/content/urlbarBindings.xml, line 677: aUrl is undefined

```
at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:118)
at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:246)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:114)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:193)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:182)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:95)
```

Error in exceptionTable[, 1] : subscript out of bounds

**Comment by greenore** [comment]
Relenium is no longer in active development. It might be better if you use the RSelenium package instead. 

https://github.com/ropensci/RSelenium
